In [12]:
import numpy as np
A=np.array([[1,2,3],[8,5,6],[3,5,7]])
b =np.array([[5], [7],[6]])
x=np.linalg.solve(A,b)
x

array([[  3.5],
       [-24. ],
       [ 16.5]])

In [44]:
import numpy as np
A=np.array([[8,5,4,8,2],[5,5,5,7,0],[7,3,7,12,0],[10,6,4,8,0],[8,7,3,8,0]])
b =np.array([[44.11116], [23.010],[29.258],[31.946],[29.402]])
x=np.linalg.solve(A,b)
x

array([[1.52   ],
       [1.201  ],
       [0.705  ],
       [0.84   ],
       [8.20308]])

In [23]:
import numpy as np
A=np.array([[8,5,4,8,1],[5,5,5,7,1],[7,3,7,12,1],[10,6,4,8,1],[8,7,3,8,1]])
b =np.array([[7680.09], [6725.44],[8792.8],[8635.72],[8049.33]])
x=np.linalg.solve(A,b)
x

array([[313.21],
       [329.21],
       [289.18],
       [304.2 ],
       [-61.96]])

In [1]:
import numpy as np
A=np.array([[5,5,5,4,1],[10,5,5,10,1],[7,4,6,5,1],[5,9,2,10,1],[5,6,4,10,1]])
b =np.array([[7456.9], [10848.2],[8342.5],[9733.4],[9323.8]])
x=np.linalg.solve(A,b)
x

array([[ 314.09130435],
       [ 317.48695652],
       [ 271.43043478],
       [ 303.47391304],
       [1727.96086957]])

In [2]:
import numpy as np
A=np.array([[5,5,5,4,1],[10,5,5,10,1],[7,4,6,5,1],[5,9,2,10,1],[5,6,4,10,1]])
b =np.array([[7961.84], [11353.09],[8852.43],[10236.34],[9827.07]])
x=np.linalg.solve(A,b)
x

array([[ 313.21],
       [ 329.21],
       [ 289.18],
       [ 304.2 ],
       [2087.04]])